#!/usr/bin/env python3
"""Generate docs/transaction_type_map.md from config + txn_types + the live extract.

Regenerate whenever the direction sets change:

    python tools/build_transaction_map.py

Generated rather than hand-written because the "reaches output" columns can only be
produced by actually running the pipelines, and they are what reveal dead codes -- types
that pass the direction rules but never survive to an output.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

import pandas as pd  # noqa: E402

from fec_newsletter import config, extract, pipelines, txn_types  # noqa: E402

RAW_15J_ROWS = 7_054_928  # excluded in SQL, so never present in the extract


def build() -> pd.DataFrame:
    paths = {n: config.CACHE_DIR / c for n, (_, c) in config.EXTRACTS.items()}
    data = extract.load(paths)

    oth = data["oth"].copy()
    oth["amount"] = pd.to_numeric(oth["TRANSACTION_AMT"], errors="coerce")
    volume = oth.groupby("TRANSACTION_TP").agg(rows=("amount", "size"), amount=("amount", "sum"))

    send, _ = pipelines.run_send(data)
    receive, _ = pipelines.run_receive(data)
    send_oth = send[send["source"] == "oth"]

    def totals(df):
        return df.groupby("transaction_tp")["amount"].agg(["size", "sum"])

    s, r = totals(send_oth), totals(receive)

    codes = sorted(
        set(volume.index)
        | set(config.OUTFLOW_TYPES) | set(config.INFLOW_TYPES) | set(config.OTH_CANDIDATE_TYPES)
        | {"15J"}
    )
    rows = []
    for tp in codes:
        treatment, reason = txn_types.classify(tp)
        rows.append({
            "code": tp,
            "treatment": treatment,
            "pipelines": txn_types.pipelines_using(tp),
            "rows": RAW_15J_ROWS if tp == "15J" else int(volume["rows"].get(tp, 0)),
            # 15J is filtered in SQL, so its dollar total was never extracted -- report it
            # as unknown rather than implying zero.
            "amount": float("nan") if tp == "15J" else float(volume["amount"].get(tp, 0.0)),
            "send_amount": float(s["sum"].get(tp, 0.0)),
            "receive_amount": float(r["sum"].get(tp, 0.0)),
            "description": txn_types.DESCRIPTIONS.get(tp, ""),
            "reason": reason,
        })
    order = {"outflow": 0, "inflow": 1, "candidate-directed": 2, "excluded": 3}
    return pd.DataFrame(rows).sort_values(
        ["treatment", "amount"],
        key=lambda s: s.map(order) if s.name == "treatment" else -s,
    )


def render(df: pd.DataFrame) -> str:
    def section(name: str, blurb: str) -> str:
        sub = df[df["treatment"] == name]
        out = [f"### {name.title()} — {len(sub)} codes\n", blurb, ""]
        out.append("| Code | Description | Used by | Rows | Amount | → send $ | → receive $ |")
        out.append("|---|---|---|---:|---:|---:|---:|")
        for _, r in sub.iterrows():
            desc = r["description"] or "_(not present in this table)_"
            amount = "_not extracted_" if pd.isna(r["amount"]) else f"${r['amount']:,.0f}"
            out.append(
                f"| `{r['code']}` | {desc} | {r['pipelines']} | {r['rows']:,} | {amount} | "
                f"${r['send_amount']:,.0f} | ${r['receive_amount']:,.0f} |"
            )
        return "\n".join(out) + "\n"

    dead = df[(df["treatment"] != "excluded") & (df["rows"] > 0)
              & (df["send_amount"] == 0) & (df["receive_amount"] == 0)]

    parts = [
        "# Transaction type map",
        "",
        "_Generated by `tools/build_transaction_map.py` — do not edit by hand._",
        "",
        f"How every `TRANSACTION_TP` in `usa.{config.OTH_TABLE}` is treated. Descriptions are "
        "verbatim from [FEC's published code list]"
        "(https://www.fec.gov/campaign-finance-data/transaction-type-code-descriptions/).",
        "",
        "The **send** pipeline attributes a newsletter from the sender's catcode. The "
        "**receive** pipeline attributes from the recipient CANDIDATE's congressional "
        "committee seats — not from a catcode, because candidates have none.",
        "",
        "**\"Used by: send + receive\" does not mean the money moves both ways.** It means "
        "both pipelines consume that transaction type, attributing the same row from "
        "opposite ends. A `24E` independent expenditure backing a member of House "
        "Agriculture counts as **the paying PAC's industry sent it** in one output and "
        "**Agri-Food policy received it** in the other — same dollar, two questions.",
        "",
        "Do not union `send_quarterly.csv` and `receive_quarterly.csv`: they are two "
        "answers about the same money, not two halves of one total.",
        "",
        "Committee-to-committee codes are **send only** — receive needs a candidate, and "
        "those rows have none on either end. Candidate-directed codes feed both.",
        "",
        "Note that *outflow / inflow* below and *send / receive* are unrelated axes. "
        "Outflow and inflow describe **which column holds the payer** inside the OTH file "
        "(`CMTE_ID` or `OTHER_ID`); send and receive describe **which pipeline** uses the "
        "row.",
        "",
        "The `→ send $` / `→ receive $` columns count only what survives to each output, and "
        "only the OTH share of send (the rest comes from PAS2). They are far below the raw "
        "amounts because most committee-to-committee money involves party and leadership-PAC "
        "catcodes, which CRP leaves outside the industry newsletters.",
        "",
        "**Classify on the description's verb, not the shape of the code.** `30K`/`31K`/`32K` "
        'are *receipts* despite sharing a `K` suffix with `24K` "Contribution **made** to '
        'nonaffiliated committee" — they were misfiled as outflows at first, which swapped '
        "sender and recipient on 824 rows worth $30.1M.",
        "",
        section("outflow", "`CMTE_ID` sent → **sender = `CMTE_ID`**, **recipient = `OTHER_ID`**. "
                           "Every description reads *made* / *out* / *to*."),
        section("inflow", "`CMTE_ID` received → **sender = `OTHER_ID`**, **recipient = `CMTE_ID`**. "
                          "Every description reads *received* / *receipt* / *in* / *from*."),
        section("candidate-directed",
                "`CMTE_ID` pays and `OTHER_ID` is a **candidate**. Feeds BOTH pipelines: "
                "send from the payer's catcode, receive from the candidate's committee "
                "seats. ~98% of these rows also appear in PAS2, which supplies most "
                "candidate money; the cross-source dedupe removes the overlap."),
        section("excluded", "Dropped by both pipelines. Reasons below."),
        "### Why each excluded code is dropped\n",
        "| Code | Reason |",
        "|---|---|",
    ]
    for _, r in df[df["treatment"] == "excluded"].iterrows():
        parts.append(f"| `{r['code']}` | {r['reason']} |")

    parts += [
        "",
        "### Included but never reaching an output",
        "",
        "These pass the direction rules yet contribute nothing — their attributed side never "
        "carries a newsletter catcode. Harmless, but worth knowing they are inert rather "
        "than assuming they carry money.",
        "",
    ]
    if len(dead):
        parts += ["| Code | Description | Rows | Amount |", "|---|---|---:|---:|"]
        for _, r in dead.iterrows():
            parts.append(f"| `{r['code']}` | {r['description']} | {r['rows']:,} | ${r['amount']:,.0f} |")
    else:
        parts.append("_None._")
    return "\n".join(parts) + "\n"


def main() -> int:
    df = build()
    dest = config.REPO_ROOT / "docs" / "transaction_type_map.md"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(render(df))
    df.to_csv(config.REPO_ROOT / "docs" / "transaction_type_map.csv", index=False)
    print(f"wrote {dest}")
    print(df.groupby("treatment").agg(codes=("code", "size"), rows=("rows", "sum")).to_string())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
