#!/usr/bin/env python3
"""Generate the send/receive draft newsletters as standalone Ghost-ready HTML.

Matches the house format used by lobby-landscapes-us/final_export: 820px body in
Segoe UI, grey-underlined h1 sections, the navy .key-takeaways and green .context
gradient blocks, and the arrow-prefixed finding lines.

Scope matches the house convention: every ranking is for ONE quarter. Only the
trend section looks back, and it does so by month rather than quarter so the
primary-to-general handover is visible.

The last column of every table is an LLM-written explanation of who the committees
are and what the pairing means, generated by tools/build_descriptions.py and cached
in cache/pac_descriptions.json. Those sentences are grounded in FEC filing facts
(committee type, disclosed sponsor, CRP industry) plus this quarter's behaviour, and
any sentence relying on outside knowledge is flagged there for review before it ships.

Three adaptations for Ghost/email delivery:
  * Bars are STATIC table HTML -- Ghost strips <script> and email clients never
    run JS, so a rendered chart would silently vanish.
  * Series colours are the validated categorical pair, NOT the house navy/green:
    that pair fails the normal-vision separation floor (dE 13.9, needs >=15), so
    readers could not tell primary from general apart.
  * Single theme, painted explicitly, because these post as email HTML.
"""
from __future__ import annotations
import html, pathlib

OUT = pathlib.Path(__file__).resolve().parents[1] / "out" / "ghost"
QUARTER = "2026 Q2"
PRIMARY, GENERAL, OTHER, TRACK = "#2a78d6", "#eb6834", "#b9c0c7", "#eef0f2"

CSS = """
body{font-family:'Segoe UI',Arial,sans-serif;max-width:820px;margin:0 auto;padding:20px;color:#1a1a1a;line-height:1.6;background:#ffffff;}
h1{color:#1a1a1a;border-bottom:2px solid #e0e0e0;padding-bottom:6px;font-size:1.35em;}
h2{color:#333;font-size:1.08em;}
a{color:#2d5a8e;}
.key-takeaways{background:linear-gradient(135deg,#1e3a5f,#2d5a8e);color:#fff;padding:18px 22px;border-radius:8px;margin-bottom:24px;}
.key-takeaways h2{color:#fff;margin-top:0;}
.context{background:linear-gradient(135deg,#1a3d2e,#2a6f4e);color:#fff;padding:18px 22px;border-radius:8px;margin-bottom:24px;}
.context h2{color:#fff;margin-top:0;}
.ctx-item{margin-bottom:14px;padding-bottom:10px;border-bottom:1px solid rgba(255,255,255,.2);}
.ctx-item:last-child{border-bottom:none;margin-bottom:0;padding-bottom:0;}
.ctx-item h3{color:#b8e6cc;margin:0 0 4px;font-size:1.03em;}
.ctx-item p{margin:0 0 6px;}
.figure{border:1px solid #e0e0e0;border-radius:8px;padding:16px 18px;margin:12px 0 4px;background:#fcfcfd;}
.figcap{font-size:.8em;color:#6b7683;margin:0 0 12px;letter-spacing:.03em;}
.legend{font-size:.8em;color:#5a6672;margin:10px 0 0;}
"""

def money(v):
    a = abs(round(v))
    s = f"${a/1e6:.1f}M" if a >= 1e6 else (f"${a/1e3:.0f}k" if a >= 1000 else f"${a:,.0f}")
    return "-" + s if v < 0 else s

def bars(rows, color):
    """Single-series magnitude bars, email-safe."""
    mx = max(abs(v) for _, v in rows) or 1
    out = ['<table style="width:100%;border-collapse:collapse;font-size:.9em;">']
    for lab, v in rows:
        pct = max(abs(v) / mx * 100, 0.6)
        out.append(
            f'<tr><td style="padding:5px 10px 5px 0;white-space:nowrap;color:#333;width:1%;">{html.escape(lab)}</td>'
            f'<td style="padding:5px 10px 5px 0;"><table style="width:100%;border-collapse:collapse;background:{TRACK};border-radius:0 3px 3px 0;">'
            f'<tr><td style="width:{pct:.1f}%;background:{color};height:10px;line-height:10px;border-radius:0 3px 3px 0;font-size:0;">&nbsp;</td>'
            f'<td style="width:{100-pct:.1f}%;font-size:0;">&nbsp;</td></tr></table></td>'
            f'<td style="padding:5px 0;text-align:right;white-space:nowrap;width:1%;">{money(v)}</td></tr>')
    return "".join(out) + "</table>"

def stacked(rows, highlight=()):
    """Monthly stacked bars: primary / general / other, with a 2px surface gap."""
    mx = max(p + g + o for _, p, g, o in rows) or 1
    out = ['<table style="width:100%;border-collapse:collapse;font-size:.85em;">']
    for lab, p, g, o in rows:
        seg = ""
        for val, col in ((p, PRIMARY), (g, GENERAL), (o, OTHER)):
            w = max(val, 0) / mx * 100
            if w <= 0:
                continue
            seg += (f'<td style="width:{w:.2f}%;background:{col};height:11px;line-height:11px;font-size:0;">&nbsp;</td>'
                    f'<td style="width:2px;font-size:0;">&nbsp;</td>')
        used = sum(max(v, 0) for v in (p, g, o)) / mx * 100
        seg += f'<td style="width:{max(100-used,0):.2f}%;font-size:0;">&nbsp;</td>'
        strong = ' font-weight:600;' if lab in highlight else ''
        out.append(
            f'<tr><td style="padding:3px 10px 3px 0;white-space:nowrap;color:#333;width:1%;{strong}">{html.escape(lab)}</td>'
            f'<td style="padding:3px 10px 3px 0;"><table style="width:100%;border-collapse:collapse;background:{TRACK};">'
            f'<tr>{seg}</tr></table></td>'
            f'<td style="padding:3px 0;text-align:right;white-space:nowrap;width:1%;{strong}">{money(p+g+o)}</td></tr>')
    out.append("</table>")
    out.append(
        f'<p class="legend"><span style="display:inline-block;width:10px;height:10px;background:{PRIMARY};"></span> Primary'
        f' &nbsp; <span style="display:inline-block;width:10px;height:10px;background:{GENERAL};"></span> General'
        f' &nbsp; <span style="display:inline-block;width:10px;height:10px;background:{OTHER};"></span> Runoff, special and other'
        f' &nbsp;&mdash;&nbsp; election designation as filed (FEC <code>TRANSACTION_PGI</code>)</p>')
    return "".join(out)

def routes(headers, rows):
    """A table whose columns are whatever the caller passes.

    Column count varies by table -- the send edition carries a recipient count the
    others do not -- so this stays generic rather than hard-coding four fields.
    Numeric columns are right-aligned by header name, and a value may be a tuple of
    (text, muted-suffix) to render a grey qualifier after the main text.
    """
    # Right-aligned columns are not all money: a recipient count is an integer that
    # must not pick up a dollar sign.
    MONEY = {"sent", "backed with", "received", "backed by"}
    COUNTS = {"recipients", "backers"}
    NUMERIC = MONEY | COUNTS
    th = ('text-align:%s;padding:0 12px 7px 0;font-size:.85em;letter-spacing:.06em;'
          'text-transform:uppercase;color:#6b7683;font-weight:600;')
    align = ["right" if h.strip().lower() in NUMERIC else "left" for h in headers]
    out = ['<table style="width:100%;border-collapse:collapse;font-size:.88em;"><tr>']
    for h, al in zip(headers, align):
        out.append(f'<th style="{th % al}">{html.escape(h)}</th>')
    out.append("</tr>")
    for row in rows:
        cells = []
        for i, (val, al) in enumerate(zip(row, align)):
            last = i == len(row) - 1
            pad = "7px 0" if last else "7px 12px 7px 0"
            colour = "color:#444;" if last else ""
            nowrap = "white-space:nowrap;" if al == "right" else ""
            if isinstance(val, tuple):
                text, muted = val
                inner = (html.escape(str(text))
                         + f'<span style="color:#6b7683;"> &middot; {html.escape(str(muted))}</span>'
                         if muted else html.escape(str(text)))
            else:
                if isinstance(val, (int, float)):
                    inner = (f"{val:,}" if headers[i].strip().lower() in COUNTS
                             else money(val))
                else:
                    inner = html.escape(str(val))
            cells.append(f'<td style="padding:{pad};border-top:1px solid #ececec;'
                         f'text-align:{al};{nowrap}{colour}">{inner}</td>')
        out.append("<tr>" + "".join(cells) + "</tr>")
    return "".join(out) + "</table>"


def figure(caption, inner):
    return f'<div class="figure"><p class="figcap">{html.escape(caption)}</p>{inner}</div>'

def note(t):
    return f"<p style='margin-left:18px;color:#444;'>&#8627; {t}</p>"

def doc(body):
    return f"<html><head><meta charset='utf-8'><style>{CSS}</style></head><body>{body}</body></html>"

# monthly (label, primary, general, other) -- other = total - P - G
SEND_M = [("Apr 2026",20294923,1215530,172000),
 ("May 2026",31680518,1900489,638575),
 ("Jun 2026",8403246,3988888,182500)]
RECV_M = [("Apr 2026",2578078,722115,25364),
 ("May 2026",5990921,1274752,318247),
 ("Jun 2026",1858593,2579234,43439)]
HL = ("Jun 2026",)

SEND = doc(f"""
<p>Each quarter we track movements in US federal campaign finance, channel by channel. This
edition covers <strong>Finance &amp; Insurance</strong> for {QUARTER}, ranking the channel's own
political action committees by what they gave, and showing who each of them backed.</p>

<div class="key-takeaways"><h2>Key Takeaways</h2>
<div class="ctx-item"><h3>Two transfers account for more than half the quarter</h3>
<p>The channel moved $68.5M in {QUARTER}, but $38.0M of that is a single pair of transfers:
Fairshake sending $19.0M each to Protect Progress and Defend American Jobs, the crypto-industry
super PACs it funds. Strip those out and the channel's quarter is $30.5M.</p></div>
<div class="ctx-item"><h3>One giver behaves nothing like the rest</h3>
<p>Fairshake sent to two recipients. Every other large giver in the channel spread its money
across hundreds: Realtors PAC across 265 recipients, the American Institute of CPAs across 190,
with no single recipient taking more than 8%.</p></div>
<div class="ctx-item"><h3>The primary season ended in June</h3>
<p>Primary-designated money fell from $31.7M in May to $8.4M in June, while general-election
money reached $4.0M, its strongest month of the quarter.</p></div></div>

<h1>Section A: Largest Senders</h1>
<p>This section ranks the Finance &amp; Insurance committees that gave the most in {QUARTER},
alongside the recipient each one principally backed. A channel edition ranks the channel's own
side: here that is the PACs doing the sending.</p>

{figure(f"Largest senders in the channel, {QUARTER}", routes(
  ["Sender", "Sent", "Recipients", "Principal recipient", "What this is"], [
  ("Fairshake", 38000000, 2, "Defend American Jobs 50% · Protect Progress 50%",
   "FAIRSHAKE, a crypto industry super PAC affiliated with Protect Progress, transferred funds to DEFEND AMERICAN JOBS, another super PAC, as part of its limited network activity this quarter."),
  ("Texas Assoc of Realtors Federal PAC", 1422000, 1, "Realtors Political Action Committee 100%",
   "TAR FEDPAC, the Texas Realtors' PAC, sent all its quarterly funds to the national REALTORS Political Action Committee, consolidating state-level real estate industry contributions at the national level."),
  ("Realtors PAC", 1192394, 265, "Realtors Political Action Committee (itself) 8%",
   "The REALTORS Political Action Committee, representing the national real estate industry, made a small direct contribution to 31 DAYS PAC, a Republican leadership PAC affiliated with Rep. Ellzey, among many other recipients this quarter."),
  ("American Institute of CPAs", 782675, 190, "American Revival PAC 1% (one of 21 tied)",
   "AICPA's PAC, representing accountants, contributed to BUILDING OUR LEADERSHIP DIVERSITY PAC, a multi-candidate PAC focused on minority and ethnic group leadership, as part of broad quarterly giving."),
  ("PricewaterhouseCoopers PAC", 686500, 126, "DNC Services Corporation/Democratic National Committee 4% · Republican National Committee - RNC 4%",
   "PricewaterhouseCoopers PAC I, representing the accounting firm, made a direct contribution to the Republican National Committee as part of its diversified quarterly spending."),
  ("National Multi Housing Council PAC", 671500, 164, "Democratic Senatorial Campaign Committee 7%",
   "The National Multi Housing Council PAC, representing real estate developers, contributed to the Democratic Senatorial Campaign Committee among many other recipients this quarter."),
]))}

<p>The quarter divides into two completely different giving styles:</p>
{note("Fairshake is 55% of the channel's entire quarter and sent to exactly two recipients, splitting $38.0M evenly between Protect Progress and Defend American Jobs.")}
{note("Every other large sender behaves the opposite way: Realtors PAC spread $1.2M across 265 recipients, the American Institute of CPAs $783k across 190, with no single recipient above 8%.")}
{note("Texas Association of Realtors is the exception among the traditional givers, moving its entire $1.4M to its own national affiliate in one transfer.")}

<h1>Section B: Contribution Trend</h1>
<p>The channel's disclosed contributions across the three months of {QUARTER}, split by the
election each was designated for. Monthly rather than a single quarter figure, because the shift
from primary to general money happened inside this quarter rather than between quarters.</p>

{figure("Monthly contributions by election designation", stacked(SEND_M, HL))}

<p>Three features stand out:</p>
{note("May was the channel's heaviest month at $34.2M, nearly all of it primary-designated.")}
{note("June marks the handover: primary money fell to $8.4M from $31.7M in May, a 73% drop in a single month as primary season closed.")}
{note("General-election money moved the other way, more than tripling from $1.2M in April to $4.0M in June &mdash; the only category to grow across the quarter.")}

<h1>Section C: How the Money Moved</h1>
<p>This section separates the quarter by transaction type. These are different kinds of money and
are never summed together: a direct contribution reaches the recipient's account, while an
independent expenditure is spent about a candidate who never receives it and cannot coordinate on it.</p>

{figure(f"{QUARTER} by flow type", bars([
  ("Committee transfers",48850984),("Direct contributions",19024750),
  ("Communication costs",596935),("Independent expenditures",4000)], PRIMARY))}
<p>Committee transfers were 71% of the quarter, against 28% in direct contributions. Independent
expenditure all but disappeared, at $4,000 for the quarter.</p>

<h2>Methodology</h2>
<p>Every figure in this report starts from one number: the <strong>transaction amount</strong> of
each contribution disclosed to the Federal Election Commission. We combine two FEC bulk files
&mdash; committee-to-committee transfers and committee-to-candidate contributions &mdash; and
remove the overlap between them, since the same transaction appears in both. Both parties to a
transfer also file it separately, so a transaction is counted once whichever side reported it.</p>
<p><strong>How a channel is assigned.</strong> A contribution counts toward the channel of the
<strong>committee that sent it</strong>, using the sending committee's CRP industry code. Only
committees whose industry we can identify are in scope. Where a code maps to more than one channel,
the full amount counts toward each, so channel totals are correct individually but should not be
added together.</p>
<p><strong>Committees CRP does not classify.</strong> Some committees that move money carry no CRP
industry code &mdash; typically newly registered ones. For those, the industry is inferred from the
committee's own FEC filing details rather than assigned by CRP, and only where that inference is
not marked low-confidence. This affects <strong>$82k of this quarter's $68.5M</strong> (0.1%), and
no committee in any table above. A CRP code always takes precedence, so no figure sourced from CRP
is altered by this.</p>
<p><strong>Election designation.</strong> The primary/general split is the designation on the filing
itself, not an inference from the date. Contributions designated for runoffs, special elections,
conventions and recounts are grouped as other.</p>
<p><strong>Reading the figures.</strong> Every figure in this edition covers {QUARTER} only,
including the monthly trend. Negative amounts are amendment reversals filed against earlier
transactions and are netted in rather than dropped. Source: FEC bulk disclosure files.</p>
""")

RECV = doc(f"""
<p>Each quarter we track movements in US federal campaign finance, channel by channel. This
edition covers <strong>Finance &amp; Insurance</strong> for {QUARTER}, ranking the members of
Congress on the channel's committee seats by the money backing them, and showing who is funding
the candidates trying to take those seats.</p>

<div class="context"><h2>Central Themes in this Quarter&rsquo;s Contribution Data</h2>
<div class="ctx-item"><h3>$12.7M backed members who write finance policy</h3>
<p>Of $15.4M reaching these seats in total, $12.7M was spent supporting the member. The rest was
spent against them, or was a campaign repaying a loan to its own candidate &mdash; neither is
industry backing, and both are separated out here.</p></div>
<div class="ctx-item"><h3>A crypto super PAC bought one seat's worth of influence</h3>
<p>Defend American Jobs supplied $1.20M of Rep. Andy Barr's (R-KY-06) $1.20M &mdash; 99% of everything backing
him, from just 14 backers in total. No other member in the channel is close to that concentrated.</p></div>
<div class="ctx-item"><h3>The biggest spending in these races is against candidates, not for them</h3>
<p>Sen. Collins' challenger raised $555k, roughly what the channel put behind Collins herself
&mdash; but faces $9.23M in opposition spending, $8.86M of it from a single PAC that discloses the
Collins Victory Committee as its connected organisation.</p></div></div>

<h1>Section A: Best-Funded Members</h1>
<p>This section ranks the members of Congress on finance seats by money spent <em>supporting</em>
them in {QUARTER}, alongside their principal backer and the seat that places them in this channel.
Money spent against a member is shown separately: it reaches the same seat but is not backing.</p>

{figure(f"Members ranked by money backing them, {QUARTER}", routes(
  ["Member", "Backed by", "Principal backer", "What this is"], [
  ("Rep. Andy Barr (R-KY-06)", 1203273, ("Defend American Jobs", "99% of 14 backers"),
   "DEFEND AMERICAN JOBS, a super PAC classified as general ideological, provided nearly all outside support received by Rep. Andy Barr this quarter."),
  ("Rep. Mike Thompson (D-CA-04)", 1151449, ("BDA PAC", "57% of 215 backers"),
   "BDA PAC, a hybrid PAC representing general business associations, was the largest single outside supporter of Rep. Mike Thompson this quarter, though he also faced opposition spending."),
  ("Rep. Ritchie Torres (D-NY-15)", 543670, ("C00923417 (unnamed)", "42% of 70 backers"),
   "A committee absent from the FEC master file provided 42% of Rep. Ritchie Torres's outside support this quarter, with no sponsor or industry on record."),
  ("Sen. Susan M. Collins (R-ME)", 472689, ("C00946921 (unnamed)", "39% of 174 backers"),
   "A committee absent from the FEC master file provided 39% of Sen. Susan Collins's outside support this quarter, with no sponsor or industry on record."),
  ("Rep. Brad Sherman (D-CA-32)", 297956, ("Valley-Westside United PAC", "79% of 89 backers"),
   "VALLEY-WESTSIDE UNITED PAC, a general ideological super PAC, was the main outside supporter of Rep. Brad Sherman this quarter, while he also faced significant opposition spending."),
]))}

<p>What the pairings show:</p>
{note("Rep. Andy Barr (R-KY-06) is the most concentrated position in the channel: 99% of the money behind him came from one committee, Defend American Jobs, against 14 backers in total.")}
{note("Rep. Mike Thompson (D-CA-04) is the opposite, drawing on 215 backers &mdash; but he also faces $695k spent against him, more than any other member here.")}
{note("Two of the five principal backers are unnamed FEC identifiers, absent from the FEC committee master file.")}
{note("Rep. Kevin Hern (R-OK-01) would rank third on raw totals, but $600k of his $604k is his own campaign repaying a loan to him. It is excluded here, as it is not industry money.")}

<h1>Section B: The Races These Seats Sit In</h1>
<p>Attribution runs through committee seats, so a member who holds one is visible to this
newsletter and a candidate trying to take it is not. This section closes that gap: for each of the
best-funded members, the candidates contesting the same seat, what was spent supporting them, and
what was spent against them. None of this money appears anywhere else in the edition.</p>

{figure(f"Money contesting the same seats, {QUARTER}", routes(
  ["Seat", "Contender", "Backed with", "Spent against them", "What this is"], [
  (("S-ME", "Sen. Collins (R)"), ("Graham Platner (D)", "challenger"), 554744, ("$9,230,161 \u2014 Pine Tree Results PAC", "17x"),
   "COMMON DEFENSE / BEYOND THE CHOIR ACTION FUND, a Democratic-aligned super PAC, made independent expenditures supporting Graham Platner, while PINE TREE RESULTS PAC, linked to the Collins Victory Committee, opposed him."),
  (("CA-04", "Rep. Thompson (D)"), ("Eric Jones (D)", "challenger"), 1261869, ("$1,310,000 \u2014 BDA PAC", "1.0x"),
   "NEW LEADERSHIP NOW, a super PAC classified as a leadership committee, spent independently to support Eric Jones, while BDA PAC, a hybrid PAC, opposed him."),
  (("CA-32", "Rep. Sherman (D)"), ("Jake Levine (D)", "challenger"), 290731, ("none", "\u2014"),
   "Committee C00945824, which has no sponsor or industry on record, made independent expenditures supporting Jake Levine in the CA-32 race. He also lent his campaign $750,000."),
  (("KY-06", "open seat"), ("Ralph Alvarado (R)", ""), 233599, ("none", "\u2014"),
   "CONSERVATIVES FOR AMERICAN EXCELLENCE INC., a Republican-aligned super PAC, made independent expenditures supporting Ralph Alvarado for the open KY-06 seat. He also lent his campaign $57,245."),
  (("KY-06", "open seat"), ("Zach Dembo (D)", ""), 261516, ("none", "\u2014"),
   "VOTEVETS, a defense policy-focused PAC, made expenditures supporting Zach Dembo for the open KY-06 seat."),
]))}

<p>Three things the races show that the seat-based ranking cannot:</p>
{note("The largest single figure anywhere in this edition is not money backing anyone. Pine Tree Results PAC \u2014 which discloses the Collins Victory Committee as its connected organisation \u2014 spent $8.86M against Sen. Collins' challenger, roughly seventeen times what he raised.")}
{note("BDA PAC and New Leadership Now are fighting each other over one seat, and both candidates are Democrats. BDA PAC put $655k behind Rep. Thompson (D) and $1.31M against Eric Jones (D); New Leadership Now put $1.26M behind Jones and $695k against Thompson.")}
{note("Rep. Barr's Kentucky seat is open rather than contested: he is running for the Senate, so the $495k backing candidates there is a fight over a seat he is leaving.")}
{note("Two contenders are partly self-funding. Jake Levine lent his campaign $750,000 and Ralph Alvarado $57,245 \u2014 loans, not contributions, and excluded from the backed-with column.")}

<h1>Section C: Arrival Trend</h1>
<p>Money reaching finance-committee seats across the three months of {QUARTER}, split by the
election each contribution was designated for.</p>

{figure("Monthly arrivals by election designation", stacked(RECV_M, HL))}

<p>Two features stand out:</p>
{note("May was the largest month of the quarter at $7.6M, roughly double the months either side of it.")}
{note("June inverts the mix: general-designated money reached $2.58M against $1.86M primary &mdash; the only month of the quarter in which general money led.")}

<h2>Methodology</h2>
<p>Every figure in this report starts from the same FEC transaction amounts as the send edition,
restricted to money whose recipient is a <strong>candidate</strong>.</p>
<p><strong>How a channel is assigned.</strong> Candidates have no industry code, so a contribution
counts toward the channel of the <strong>congressional committees its recipient sits on</strong>. We
join the FEC candidate ID to the sitting member, then to their current committee and subcommittee
assignments, then to the channels those assignments cover. Attribution is at subcommittee level
where a member holds a subcommittee seat, since &ldquo;Capital Markets&rdquo; is a sharper signal
than &ldquo;Financial Services&rdquo;.</p>
<p><strong>Backing is not the same as arriving.</strong> An independent expenditure spent
<em>against</em> a member reaches that member's seat but is not money backing them, and a campaign
repaying a loan to its own candidate is not industry money at all. Section A ranks on supporting
money only and reports opposition separately; the $15.4M headline is everything reaching these
seats, and the two figures are not interchangeable.</p>
<p><strong>How the money is divided.</strong> A member typically sits on several committees, and a
committee may cover several channels. Rather than credit the full amount to each &mdash; which would
count the same dollars repeatedly &mdash; we divide a contribution <strong>evenly</strong> across the
member's committees, and then evenly again across the channels each committee covers. Channel
totals in this edition therefore add up without double-counting.</p>
<p><strong>The races.</strong> Section B leaves the committee-seat attribution behind. Candidates
are matched to a seat by office, state and district from the FEC candidate master, and the
incumbent, challenger and open-seat labels are the FEC's own. Because these candidates hold no
committee seat, their money belongs to no channel and is reported only in the context of the seat
being contested.</p>
<p><strong>Coverage.</strong> In {QUARTER}, $289.3M of the $396.4M in candidate contributions went
to challengers, open-seat candidates and defeated incumbents. Section B recovers part of that for
the seats ranked here; the rest is outside this edition.</p>
<p><strong>Relationship to the send edition.</strong> The two are not two halves of one total and
should not be added. This edition selects money whose RECIPIENT sits on a finance seat, whoever
sent it; the send edition selects money whose SENDER is a finance committee, whoever received it.
In {QUARTER} they share 4,345 transactions &mdash; 21% of this edition's rows and 48% of the send
edition's &mdash; and no ranked entity appears in both. Source: FEC bulk disclosure files and the
unitedstates/congress-legislators dataset.</p>
""")

if __name__ == "__main__":
    OUT.mkdir(parents=True, exist_ok=True)
    for name, content in (("Finance_and_Insurance_SEND", SEND),
                          ("Finance_and_Insurance_RECEIVE", RECV)):
        p = OUT / f"{name}.html"
        p.write_text(content, encoding="utf-8")
        print(f"wrote {p}  ({len(content):,} bytes)")
